- name: "Bug: Already Fixed"
  description: "Issues that report already fixed bugs."
  color: "B3E88C"
- name: "Bug: Cannot Reproduce"
  description: "Issues that report bugs that cannot be reproduced."
  color: "f9d0c4"
- name: "Bug: Confirmed"
  description: "Issues that report confirmed bugs."
  color: "f9d0c4"
- name: "Bug: Fixed"
  description: "Issues that report bugs and have been fixed."
  color: "00fa9a"
- name: "Bug: Pending Response"
  description: "Issues that report bugs and are pending of a response from the author."
  color: "f9d0c4"
- name: "Bug: Unverified"
  description: "Issues that report unverified bugs. Pending for inspection."
  color: "f9d0c4"
- name: "Semver: Major"
  description: "PRs that contain breaking changes and should be released in the next major version."
  color: "c10f47"
- name: "Semver: Minor"
  description: "PRs that contain new features and should be released in the next minor version."
  color: "e4f486"
- name: "Semver: Patch"
  description: "PRs that contain bugfixes and should be released in the next patch version."
  color: "e8be8b"
- name: "Meta: Dependencies"
  description: "Issues and PRs related to dependencies."
  color: "ffff00"
- name: "Meta: Feature"
  description: "Issues and PRs related to new features."
  color: "ffff00"
- name: "Meta: BugFix"
  description: "PRs that fix bugs or issues."
  color: "4cce4a"
- name: "Meta: Cleanup"
  description: "Issues and PRs related to code cleanup."
  color: "ffff00"
- name: "Meta: Documentation"
  description: "Issues and PRs related to documentation."
  color: "ffff00"
- name: "Meta: Examples"
  description: "Issues and PRs related to examples."
  color: "ffff00"
- name: "Meta: GitHub"
  description: "Issues and PRs related to GitHub."
  color: "ffff00"
- name: "Meta: Refactor"
  description: "Issues and PRs related to refactors."
  color: "ffff00"
- name: "Priority: Critical"
  description: "Issues and PRs with maximum priority."
  color: "b60205"
- name: "Priority: High"
  description: "Issues and PRs with high priority."
  color: "d93f0b"
- name: "Priority: Medium"
  description: "Issues and PRs with medium priority."
  color: "fbca04"
- name: "Priority: Low"
  description: "Issues and PRs with low priority."
  color: "0e8a16"
- name: "Priority: Ultra-Low"
  description: "Issues and PRs with such a low priority it could be finished long after creation."
  color: "818181"
